
const programmingSkills = [
    { id: 1, name: 'HTML' },
    { id: 2, name: 'CSS' },
    { id: 3, name: 'JavaScript' },
    { id: 4, name: 'Python' },
    { id: 5, name: 'Java' },
    { id: 6, name: 'C++' },
    { id: 7, name: 'C#' },
    { id: 8, name: 'React.js' },
    { id: 9, name: 'Node.js' },
    { id: 10, name: 'PHP' },
    { id: 11, name: 'Vue.js' },
    { id: 12, name: 'GIT' },
    { id: 13, name: 'MySQL' },
    { id: 14, name: 'UI/UX' },
    { id: 15, name: 'Data Science' },
    { id: 16, name: 'MongoDB' },
    { id: 17, name: 'Ruby' },
    { id: 18, name: 'Angular' },
    { id: 19, name: 'Security Best Practices' },
    { id: 20, name: 'Testing and Debugging' },
    { id: 21, name: 'Command Line/CLI' },
    { id: 22, name: 'Database Management' },
    { id: 23, name: 'Responsive Web Design' },
    { id: 24, name: 'Front-End Frameworks and Libraries' },
    { id: 25, name: 'Problem Solving and Troubleshooting' },
  ];

  export default programmingSkills;